# Generated by Django 4.2.4 on 2023-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oLat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('oLon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('dLat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('dLon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
