# Generated by Django 4.1.7 on 2023-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stat',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
