# Generated by Django 4.1.7 on 2023-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ppic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
