services:
  backend:
    # container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000  # Expose Django app's port
    volumes:
      - ./backend:/app
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80  # Expose Nginx port
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx configuration file
    depends_on:
      - backend